on: [push, pull_request]

name: CI

jobs:
  check:
    name: Run tests and clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: cargo clippy
        run: cargo clippy -- -D warnings

      - name: cargo test
        run: cargo test

  check-no_std:
    name: Check no_std
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install toolchain
        run: rustup target add aarch64-unknown-none

      - name: cargo check
        run: cargo check --target aarch64-unknown-none --no-default-features --features ahash

  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: cargo fmt -- --check
        run: cargo fmt -- --check
