on: [push, pull_request]

name: CI

jobs:
  check:
    name: Run tests and clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: cargo clippy
        run: cargo clippy -- -D warnings

      - name: cargo test
        run: cargo test

  check-no_std:
    name: Check no_std
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: aarch64-unknown-none
          toolchain: stable
          override: true

      - name: cargo check
        run: cargo check --target aarch64-unknown-none --no-default-features --features ahash

  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: cargo fmt -- --check
        run: cargo fmt -- --check
